"""добавил столбец  фотографии для таблицы Tour

Revision ID: 25021d8b37ad
Revises: dba9e2dee9e8
Create Date: 2026-01-02 17:06:57.373229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25021d8b37ad'
down_revision: Union[str, Sequence[str], None] = 'dba9e2dee9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tours', 'image_url')
    # ### end Alembic commands ###
