"""валидацию изменил в Tour т.к мешали

Revision ID: 5a40902c4f26
Revises: d8ffe5df442d
Create Date: 2026-01-02 18:40:11.342974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a40902c4f26'
down_revision: Union[str, Sequence[str], None] = 'd8ffe5df442d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
