"""додела весь проект и БД убарл старое оптимизировал взаимодействие между моделями

Revision ID: 8ef5e5659af2
Revises: f4c16d20ab41
Create Date: 2026-02-02 21:12:56.621626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef5e5659af2'
down_revision: Union[str, Sequence[str], None] = 'f4c16d20ab41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
