"""изменил стобец duration в ТУре на строку так проще

Revision ID: b092de091a59
Revises: 25021d8b37ad
Create Date: 2026-01-02 17:51:35.668903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b092de091a59'
down_revision: Union[str, Sequence[str], None] = '25021d8b37ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('duration', sa.String(length=25), nullable=False, comment='Продолжительность тура'))
    op.drop_column('tours', 'duration_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('duration_hours', sa.INTEGER(), autoincrement=False, nullable=False, comment='Продолжительность в часах'))
    op.drop_column('tours', 'duration')
    # ### end Alembic commands ###
