"""Initial tables

Revision ID: dba9e2dee9e8
Revises: 
Create Date: 2026-01-01 17:51:25.990741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba9e2dee9e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landmarks_name'), 'landmarks', ['name'], unique=False)
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=False, comment='Цена за человека в рублях'),
    sa.Column('max_people', sa.Integer(), nullable=False),
    sa.Column('booked_seats', sa.Integer(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False, comment='Продолжительность в часах'),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('meeting_point', sa.String(length=500), nullable=True, comment='Место встречи'),
    sa.Column('meeting_time', sa.String(length=50), nullable=True, comment='Время встречи'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('duration_hours > 0', name='check_duration_positive'),
    sa.CheckConstraint('max_people > 0', name='check_max_people_positive'),
    sa.CheckConstraint('price_per_person > 0', name='check_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_category'), 'tours', ['category'], unique=False)
    op.create_index(op.f('ix_tours_id'), 'tours', ['id'], unique=False)
    op.create_index(op.f('ix_tours_name'), 'tours', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('telegram_id > 0', name='check_telegram_id_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='order_status'), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_id', sa.String(length=200), nullable=True, comment='ID платежа в платежной системе'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(cancelled_at IS NULL) OR (confirmed_at IS NULL)', name='check_mutually_exclusive_timestamps'),
    sa.CheckConstraint('quantity > 0', name='check_order_quantity_positive'),
    sa.CheckConstraint('total_price >= 0', name='check_total_price_non_negative'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booked_at', 'orders', ['booked_at'], unique=False)
    op.create_index('idx_user_tour_status', 'orders', ['user_id', 'tour_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tour_id'), 'orders', ['tour_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('tour_landmark_association',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('landmark_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tour_id', 'landmark_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_landmark_association')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_tour_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('idx_user_tour_status', table_name='orders')
    op.drop_index('idx_booked_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tours_name'), table_name='tours')
    op.drop_index(op.f('ix_tours_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_category'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_landmarks_name'), table_name='landmarks')
    op.drop_table('landmarks')
    # ### end Alembic commands ###
