"""создал модель банеров для меню + в Order добавил поле типа оплаты

Revision ID: f4c16d20ab41
Revises: d17f4fe624df
Create Date: 2026-01-16 19:08:17.039439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c16d20ab41'
down_revision: Union[str, Sequence[str], None] = 'd17f4fe624df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_type', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_type')
    # ### end Alembic commands ###
